### ISSUE TITLE
How to add custom header?

### ISSUE THREAD

**Issue by dheerajbred** [lytian/m3u8_downloader#1]
How to download a video with request headers? Is there a way to headers for download request?

I added `conn.addRequestProperty("Referer", "http://xxxxxxxx.com/");` to M3U8DownloadTask.java but that didn't do it.

Any help is really appreciated

**Comment by lytian** [comment]
Are you sure the header value is correct?

You can use "Postman" to test whether it can be acquired normally.

**Comment by dheerajbred** [comment]
http://xxxxxxxx.com/ is just an example. I checked. The video does work only with a request header.  Is there a way to headers for download requests?

**Comment by lytian** [comment]
There are two types of network requests in the project, m3u8 and TS files.

**M3U8DownloadTask.java** ， It's just for TS Download.

**MUtils.java => parseIndex(String url)**,  It uses BufferedReader and URL to read the contents of the file.
```java
// you can fix it
BufferedReader reader = new BufferedReader(new InputStreamReader(new URL(url).openStream()));
```

**Comment by dheerajbred** [comment]
Thanks. This helps :)
