### ISSUE TITLE
合并后的mp4播放有问题

### ISSUE THREAD

**Issue by JaredLees** [lytian/m3u8_downloader#13]
加密后的m3u8, 合并后的mp4视频播放画面卡顿，有时候只有声音，画面卡住。

**Comment by JaredLees** [comment]
测试连接：https://vod2.buycar5.cn/20201108/bkR5bLKK/index.m3u8

**Comment by lytian** [comment]
我晚上试一下

**Comment by lytian** [comment]
本项目是直接通过ts文件读写到mp4文件，所以对有些视频不太兼容。你可以：
1. 不转成MP4，直接使用本地m3u8播放；
2. 使用ffmpeg
