### ISSUE TITLE
Advice on multiple downloading

### ISSUE THREAD

**Issue by Marklaverda** [lytian/m3u8_downloader#14]
Hello Lytian,
Is there a workaround way to implement multiple downloads?
I would like to discuss some additional coding and how I can employ you to assist as a consultant.
Regards
Mark

**Comment by lytian** [comment]
Multiple download is not supported, because it is multi TS task download.

If you want, a m3u8 download is a [M3U8DownloadTask](https://github.com/lytian/m3u8_downloader/blob/master/android/src/main/java/com/vincent/m3u8Downloader/downloader/M3U8DownloadTask.java) task，you can mange it.

**Comment by Marklaverda** [comment]
Hello
Thank you for your kind response.
We will try this and hopefully resolve it.
Do you do consultancy work?
Thank you!

**Comment by lytian** [comment]
No. I suggest you fork the code

**Comment by Marklaverda** [comment]
Ok, thanks. Have a great day.

**Comment by lytian** [comment]
If I knew, I would answer.
