### ISSUE TITLE
 I/flutter (24963): {totalFormatSize: , totalSize: 0, formatSpeed: 916 KB/s, progress: 0, currentFormatSize: , url: https://cdn.zoubuting.com/20210709/tqzA6eQ7/index.m3u8, speed: 938186, status: 1} #1 

### ISSUE THREAD

**Issue by wangxude** [lytian/m3u8_downloader#16]
您好，我用您那个下载m3u8的flutter的demo时候，debug包可以正常回调，release包不能正常回调，回调进度始终是0.。您可以帮忙看看吗

**Comment by lytian** [comment]
Release下也能够正常回调进度的。
![image](https://user-images.githubusercontent.com/5880204/169014861-e7a818a2-50b1-4f45-b6f8-3f95a27d040e.png)

**Comment by wangxude** [comment]
<img width="1236" alt="图片" src="https://user-images.githubusercontent.com/21336930/169047808-c14554f2-0cfd-4736-a4e1-9628bdf99273.png">

**Comment by wangxude** [comment]
我这里debug模式都好使。release就不好用了。博主可以帮我看看吗，我的微信18131371659

**Comment by lytian** [comment]
已解决
