### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified

### ISSUE THREAD

**Issue by nnianhouss** [lytian/m3u8_downloader#17]
targetSdkVersion 31 下载完报错

`W/System.err(31735): java.lang.IllegalArgumentException: com.cmxc.eggplanet: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
W/System.err(31735): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
W/System.err(31735): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
W/System.err(31735): 	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
W/System.err(31735): 	at android.app.PendingIntent.getActivity(PendingIntent.java:444)
W/System.err(31735): 	at android.app.PendingIntent.getActivity(PendingIntent.java:408)
W/System.err(31735): 	at com.vincent.m3u8Downloader.utils.NotificationUtil.updateNotification(NotificationUtil.java:114)
W/System.err(31735): 	at com.vincent.m3u8Downloader.M3U8DownloaderPlugin$2.onDownloadSuccess(M3U8DownloaderPlugin.java:240)
W/System.err(31735): 	at com.vincent.m3u8Downloader.downloader.M3U8Downloader$1.onSuccess(M3U8Downloader.java:216)
W/System.err(31735): 	at com.vincent.m3u8Downloader.downloader.M3U8DownloadTask$3.run(M3U8DownloadTask.java:167)
W/System.err(31735): java.lang.IllegalArgumentException: com.cmxc.eggplanet: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
W/System.err(31735): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
W/System.err(31735): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
W/System.err(31735): 	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
W/System.err(31735): 	at android.app.PendingIntent.getActivity(PendingIntent.java:444)
W/System.err(31735): 	at android.app.PendingIntent.getActivity(PendingIntent.java:408)
W/System.err(31735): 	at com.vincent.m3u8Downloader.utils.NotificationUtil.updateNotification(NotificationUtil.java:114)
W/System.err(31735): 	at com.vincent.m3u8Downloader.M3U8DownloaderPlugin$2.onDownloadSuccess(M3U8DownloaderPlugin.java:240)
W/System.err(31735): 	at com.vincent.m3u8Downloader.downloader.M3U8Downloader$1.onSuccess(M3U8Downloader.java:216)
W/System.err(31735): 	at com.vincent.m3u8Downloader.downloader.M3U8DownloadTask$3.run(M3U8DownloadTask.java:167)
W/System.err(31735): java.lang.IllegalArgumentException: com.cmxc.eggplanet: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
W/System.err(31735): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
W/System.err(31735): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
W/System.err(31735): 	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
W/System.err(31735): 	at android.app.PendingIntent.getActivity(PendingIntent.java:444)
W/System.err(31735): 	at android.app.PendingIntent.getActivity(PendingIntent.java:408)
W/System.err(31735): 	at com.vincent.m3u8Downloader.utils.NotificationUtil.updateNotification(NotificationUtil.java:114)
W/System.err(31735): 	at com.vincent.m3u8Downloader.M3U8DownloaderPlugin$2.onDownloadSuccess(M3U8DownloaderPlugin.java:240)
W/System.err(31735): 	at com.vincent.m3u8Downloader.downloader.M3U8Downloader$1.onSuccess(M3U8Downloader.java:216)
W/System.err(31735): 	at com.vincent.m3u8Downloader.downloader.M3U8DownloadTask$3.run(M3U8DownloadTask.java:167)`

**Comment by lytian** [comment]
参考[stackoverflow的回答](https://stackoverflow.com/questions/69783824/targeting-s-version-31-and-above-requires-that-one-of-flag-immutable-or-flag)

Add the following to your build.gradle(app) dependencies.
```gradle
dependencies {
  // For Java
  implementation 'androidx.work:work-runtime:2.7.1' 

  // For Kotlin
  implementation 'androidx.work:work-runtime-ktx:2.7.1'
}
```
