### ISSUE TITLE
非常好，请问能支持多任务下载和MP4下载吗？

### ISSUE THREAD

**Issue by nowexhas** [lytian/m3u8_downloader#3]
单任务好像无法满足目前多数应用场景，还有MP4/FLV格式支持，相信是很有潜力的。

**Comment by lytian** [comment]
M3U8本来就是是多任务下载，ts片段多任务下载。下载mp4/FLV等常规文件，你可以使用dio的download方法

**Comment by nowexhas** [comment]
几个m3u8同时下载支持吗？另外想请问下，如何对下载的多个任务进行管理？感谢～～

**Comment by lytian** [comment]
一个m3u8视频流，里面包含了很多ts片段，下载时，是对ts片段进行多任务下载。

**Comment by jooftes** [comment]
ts分片多任务这个是看懂了，我想问的是多个m3u8同时下载支持吗？另外想请问的是如何对下载的多个任务进行管理？如下载状态，因为您demo中没相关示例～～

**Comment by nowexhas** [comment]
ts分片多任务这个是看懂了，我想问的是多个m3u8同时下载支持吗？另外想请问的是如何对下载的多个任务进行管理？如下载状态，因为您demo中没相关示例～～

**Comment by lytian** [comment]
不支持多个m3u8同时下载。

**Comment by lytian** [comment]
通过设置callback，获取下载状态。demo示例：https://github.com/lytian/m3u8_downloader/blob/master/example/lib/main.dart

**Comment by nowexhas** [comment]
> 通过设置callback，获取下载状态。demo示例：https://github.com/lytian/m3u8_downloader/blob/master/example/lib/main.dart

好的，有计划支持多M3U8下载吗？

**Comment by lytian** [comment]
暂时没有，可以fork代码自己尝试处理一下。不过我现在正在做下载进度通知
