### ISSUE TITLE
下载完成后,可以播放么,

### ISSUE THREAD

**Issue by hanxuefengshuang** [lytian/m3u8_downloader#4]
到文件夹有一堆TS文件,但是播放要先合成一个文件吧,再用其他播放器把合成好的文件传给他,这个功能打算做嘛

**Comment by lytian** [comment]
使用video_player插件可以播放，播放地址是`M3u8Downloader.getM3U8Path(url)`。

转成mp4功能后续可能会考虑，暂时没计划

**Comment by lytian** [comment]
@hanxuefengshuang 转成MP4功能已做

**Comment by hanxuefengshuang** [comment]
非常感谢,这对我们很有帮助,也可以打开路劲里的local.m3u8文件也是可以播放的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lytian/m3u8_downloader"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月9日(星期天) 下午5:01
收件人:&nbsp;"lytian/m3u8_downloader"<m3u8_downloader@noreply.github.com&gt;;
抄送:&nbsp;"寰宇"<172998819@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [lytian/m3u8_downloader] 下载完成后,可以播放么, (#4)





 
@hanxuefengshuang 转成MP4功能已做
