### ISSUE TITLE
（初试化 isConvert: true时）下载成功回调 返回的 fileName 不应该是.m3u8!理应是.mp4 我在本地查看数据，只有.mp4文件了

### ISSUE THREAD

**Issue by wumingman** [lytian/m3u8_downloader#6]
![image](https://user-images.githubusercontent.com/17715408/89773407-6c4e2900-db36-11ea-87e8-0245a9197480.png)

**Comment by lytian** [comment]
BUG已处理，同时也修改了success回调参数名称
