### ISSUE TITLE
退出应用再打开Plugin方法丢失

### ISSUE THREAD

**Issue by nowexhas** [lytian/m3u8_downloader#7]
`[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getM3U8Path on channel vincent/m3u8_downloader)`

作者好，测试中发现在debug和release中都会有几率出现该问题：
第一次打开应用plugin方法正常，退出应用再打开时会报这个错，通信失败。

搜了一下不知是不是这个原因？[https://juejin.im/post/6844904040975990791](https://juejin.im/post/6844904040975990791)

测试彻底杀掉进程再开应用正常，不杀进程再打开应用一直报这个错。

更新：暂停任务的时候会有如下错误：

W/System.err(14974): java.io.InterruptedIOException: thread interrupted
W/System.err(14974):    at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:147)
W/System.err(14974):    at com.android.okhttp.okio.Okio$2.read(Okio.java:135)
W/System.err(14974):    at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
W/System.err(14974):    at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
W/System.err(14974):    at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:395)
W/System.err(14974):    at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:372)
W/System.err(14974):    at java.io.InputStream.read(InputStream.java:101)
W/System.err(14974):    at vincent.m3u8_downloader.M3U8DownloadTask$4.run(M3U8DownloadTask.java:325)
W/System.err(14974):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(14974):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(14974):    at java.lang.Thread.run(Thread.java:919)
W/System.err(14974): java.io.InterruptedIOException: thread interrupted
W/System.err(14974):    at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:147)
W/System.err(14974):    at com.android.okhttp.okio.Okio$2.read(Okio.java:135)
W/System.err(14974):    at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
W/System.err(14974):    at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
W/System.err(14974):    at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:395)
W/System.err(14974):    at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:372)
W/System.err(14974):    at java.io.InputStream.read(InputStream.java:101)
W/System.err(14974):    at vincent.m3u8_downloader.M3U8DownloadTask$4.run(M3U8DownloadTask.java:325)
W/System.err(14974):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(14974):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(14974):    at java.lang.Thread.run(Thread.java:919)

**Comment by lytian** [comment]
方法找不到应该不是那个你指的问题。你在执行下载前有加上这句代码`WidgetsFlutterBinding.ensureInitialized();`吗？

暂停任务时，确实会中断线程，这里没做处理。

**Comment by nowexhas** [comment]
> 方法找不到应该不是那个你指的问题。你在执行下载钱有加上这句代码`WidgetsFlutterBinding.ensureInitialized();`吗？
> 
> 暂停任务时，确实会中断线程，这里没做处理。

已经添加`WidgetsFlutterBinding.ensureInitialized();`，我再试试～～。
